version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=mouse_shop
    ports:
      - "8000:8000"

  frontend-user:
    build: 
      context: ./frontend-user
      dockerfile: Dockerfile
    volumes:
      - ./frontend-user:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mouse_shop
    volumes:
      - ./backend/mysql/db/mouse_shop.sql:/docker-entrypoint-initdb.d/mouse_shop.sql
    ports:
      - "3306:3306"